runtime: nodejs12

automatic_scaling:
  max_instances: 2
  max_idle_instances: 1

env_variables:
  GOOGLE_CLOUD_PROJECT: mioi-egginc
  GCLOUD_STORAGE_BUCKET: mioi-egginc-public

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301